services:
  eclipsejdtls:
    image: truongbui2002/eclipsejdtls
    platform: linux/amd64
    command: [
      "bash", "-c", "npm install && npm run start:example:server:jdtls"
    ]
    ports:
      - 30003:30003
    working_dir: /home/mlc
    container_name: eclipsejdtls