replicaCount: 1

image:
  repository: rabbitmq
  tag: "4.0-management"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  ports:
    amqp: 5672
    management: 15672

persistence:
  enabled: true
  storageClass: null # Sử dụng StorageClass mặc định nếu chưa có
  accessModes:
    - ReadWriteOnce
  size: 5Gi

rabbitmq:
  username: icodervn
  password: icodervn

securityContext:
  enabled: true
  fsGroup: 1000

resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "250m"
    memory: "256Mi"

initContainer:
  enabled: true
  image: busybox
  tag: "latest"
  command:
    - sh
    - -c
    - chown -R 1000:1000 /var/lib/rabbitmq