apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: course-postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-retain
  resources:
    requests:
      storage: 8Gi